---
title: "linear regression"
author: "xj2249"
date: "11/7/2019"
output: html_document
---

```{r}
library(tidyverse)
library(p8105.datasets)

set.seed(1)
```

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    boro = neighbourhood_group,
    neighborhood = neighbourhood) %>% 
  filter(boro != "Staten Island") %>% 
  select(price, stars, boro, neighborhood, room_type)
nyc_airbnb %>% view()
```

```{r}
fit <- lm(price ~ stars + boro, data = nyc_airbnb)
fit %>% 
        broom::tidy() %>% 
        mutate(term = str_replace(term, "boro","Boro:"))
```

take a look at factors
```{r}
nyc_airbnb <- 
        nyc_airbnb %>% 
        mutate(boro = fct_infreq(boro),
               room_type = fct_infreq(room_type)
               )
```

refit the model
```{r}
fit <- lm(price ~ stars + boro, data = nyc_airbnb)
fit %>% broom::tidy()
fit %>% broom::glance() %>% view()

```

## diagnosis
```{r}
# about looking at your residual
modelr::add_residuals(nyc_airbnb,fit) %>% 
        summarise(mean = mean(resid,na.rm = T))

modelr::add_predictions(nyc_airbnb,fit)
```


## add anova test (skipped )
```{r}

```


## nesting 
Jeff loves nesting...
```{r}
fit_interaction = lm(price ~ stars * boro + room_type * boro, data = nyc_airbnb)

fit_interaction %>%
        broom::tidy()
```

## try map
```{r}
nyc_airbnb %>% 
        nest(data = -boro) %>% 
        mutate(
               models =  map(.x = data, ~lm(price ~ stars + room_type, data = .x)),
               result = map(models,broom::tidy)
        ) %>% 
        select(boro,result) %>% 
        unnest(result)
```


## nest neighborhoods
```{r}
manhattan_nest_lm <-
        nyc_airbnb %>% 
        filter(boro == "Manhattan") %>% 
        nest(data = -neighborhood) %>% 
        mutate(
               models =  map(.x = data, ~lm(price ~ stars + room_type, data = .x)),
               result = map(models,broom::tidy)
        ) %>% 
        select(neighborhood,result) %>% 
        unnest(result)
# if we just use "*" in the model, it's going to hard to interpret the result, so we seperately use the model in different neighborhood.
```



```{r}
manhattan_nest_lm %>%
```

